package com.example.gui;

import java.awt.event.ActionListener;

/**
 *
 * @author DARWIN
 */
public class Calculadora extends javax.swing.JFrame {
    
    private String cadenaNumeros="";
    private String operacion = "nula";
    private double primerNumero, resultado;
    private boolean activado = true;
    private boolean punto = true;

    
    public Calculadora() {
        initComponents();
        this.setTitle("Calculadora");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonMC = new javax.swing.JButton();
        botonMR = new javax.swing.JButton();
        botonMS = new javax.swing.JButton();
        BotonMmas = new javax.swing.JButton();
        BotonMmenos = new javax.swing.JButton();
        numero7 = new javax.swing.JButton();
        numero8 = new javax.swing.JButton();
        numero9 = new javax.swing.JButton();
        BotonR = new javax.swing.JButton();
        BotonC = new javax.swing.JButton();
        numero4 = new javax.swing.JButton();
        numero5 = new javax.swing.JButton();
        numero6 = new javax.swing.JButton();
        BotonMas = new javax.swing.JButton();
        BotonDivision = new javax.swing.JButton();
        numero1 = new javax.swing.JButton();
        numero2 = new javax.swing.JButton();
        numero3 = new javax.swing.JButton();
        botonMenos = new javax.swing.JButton();
        botonMultiplicar = new javax.swing.JButton();
        numero0 = new javax.swing.JButton();
        botonPunto = new javax.swing.JButton();
        botonIgual = new javax.swing.JButton();
        EtiquetaNumeros = new javax.swing.JLabel();
        etiquetaMostrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonMC.setBackground(new java.awt.Color(102, 102, 102));
        botonMC.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botonMC.setText("MC");

        botonMR.setBackground(new java.awt.Color(102, 102, 102));
        botonMR.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botonMR.setText("MR");
        botonMR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMRActionPerformed(evt);
            }
        });

        botonMS.setBackground(new java.awt.Color(102, 102, 102));
        botonMS.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botonMS.setText("MS");

        BotonMmas.setBackground(new java.awt.Color(102, 102, 102));
        BotonMmas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BotonMmas.setText("M+");

        BotonMmenos.setBackground(new java.awt.Color(102, 102, 102));
        BotonMmenos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BotonMmenos.setText("M-");

        numero7.setBackground(new java.awt.Color(153, 153, 153));
        numero7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        numero7.setText("7");
        numero7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero7ActionPerformed(evt);
            }
        });

        numero8.setBackground(new java.awt.Color(153, 153, 153));
        numero8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        numero8.setText("8");
        numero8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero8ActionPerformed(evt);
            }
        });

        numero9.setBackground(new java.awt.Color(153, 153, 153));
        numero9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        numero9.setText("9");
        numero9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero9ActionPerformed(evt);
            }
        });

        BotonR.setBackground(new java.awt.Color(102, 102, 102));
        BotonR.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BotonR.setText("R");
        BotonR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRActionPerformed(evt);
            }
        });

        BotonC.setBackground(new java.awt.Color(102, 102, 102));
        BotonC.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BotonC.setText("C");
        BotonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCActionPerformed(evt);
            }
        });

        numero4.setBackground(new java.awt.Color(153, 153, 153));
        numero4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        numero4.setText("4");
        numero4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero4ActionPerformed(evt);
            }
        });

        numero5.setBackground(new java.awt.Color(153, 153, 153));
        numero5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        numero5.setText("5");
        numero5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero5ActionPerformed(evt);
            }
        });

        numero6.setBackground(new java.awt.Color(153, 153, 153));
        numero6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        numero6.setText("6");
        numero6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero6ActionPerformed(evt);
            }
        });

        BotonMas.setBackground(new java.awt.Color(102, 102, 102));
        BotonMas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BotonMas.setText("+");
        BotonMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMasActionPerformed(evt);
            }
        });

        BotonDivision.setBackground(new java.awt.Color(102, 102, 102));
        BotonDivision.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BotonDivision.setText("/");
        BotonDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDivisionActionPerformed(evt);
            }
        });

        numero1.setBackground(new java.awt.Color(153, 153, 153));
        numero1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        numero1.setText("1");
        numero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero1ActionPerformed(evt);
            }
        });

        numero2.setBackground(new java.awt.Color(153, 153, 153));
        numero2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        numero2.setText("2");
        numero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero2ActionPerformed(evt);
            }
        });

        numero3.setBackground(new java.awt.Color(153, 153, 153));
        numero3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        numero3.setText("3");
        numero3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero3ActionPerformed(evt);
            }
        });

        botonMenos.setBackground(new java.awt.Color(102, 102, 102));
        botonMenos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botonMenos.setText("-");
        botonMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenosActionPerformed(evt);
            }
        });

        botonMultiplicar.setBackground(new java.awt.Color(102, 102, 102));
        botonMultiplicar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botonMultiplicar.setText("*");
        botonMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMultiplicarActionPerformed(evt);
            }
        });

        numero0.setBackground(new java.awt.Color(153, 153, 153));
        numero0.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        numero0.setText("0");
        numero0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero0ActionPerformed(evt);
            }
        });

        botonPunto.setBackground(new java.awt.Color(153, 153, 153));
        botonPunto.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botonPunto.setText(".");
        botonPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPuntoActionPerformed(evt);
            }
        });

        botonIgual.setBackground(new java.awt.Color(102, 102, 102));
        botonIgual.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        botonIgual.setText("=");
        botonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIgualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numero7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numero4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(numero8, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numero9, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(numero5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numero6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(botonMC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonMR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonMS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonMmas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonMmenos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(numero1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numero2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(numero0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(numero3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonPunto, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BotonMas, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotonDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botonMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(botonIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BotonR, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotonC, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonMmenos, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonMmas, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonMS, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonMR, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonMC, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(numero7, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numero8, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numero9, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BotonR, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BotonC, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(numero4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numero5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numero6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BotonMas, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BotonDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(numero1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numero2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numero3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(numero0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonPunto, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        EtiquetaNumeros.setBackground(new java.awt.Color(204, 204, 204));
        EtiquetaNumeros.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        EtiquetaNumeros.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        EtiquetaNumeros.setText("0");

        etiquetaMostrar.setBackground(new java.awt.Color(204, 204, 204));
        etiquetaMostrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        etiquetaMostrar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(etiquetaMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EtiquetaNumeros, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(etiquetaMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EtiquetaNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonMRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonMRActionPerformed

    private void BotonRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRActionPerformed
        int tamanio=cadenaNumeros.length();
        if(tamanio>0){
            if(tamanio==1){
                cadenaNumeros="0";
            }else{
                cadenaNumeros=cadenaNumeros.substring(0,cadenaNumeros.length()-1);
            }
            EtiquetaNumeros.setText(cadenaNumeros);
        }
        
    }//GEN-LAST:event_BotonRActionPerformed

    private void botonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIgualActionPerformed
        double segundoNumero;
        if (operacion.equals("nula")) {
            EtiquetaNumeros.setText(cadenaNumeros);
            
        } else if (operacion.equals("sumar")) {
            segundoNumero = Double.parseDouble(cadenaNumeros);
            resultado = primerNumero + segundoNumero;
            EtiquetaNumeros.setText(String.format("%.2f", resultado));
            cadenaNumeros = String.valueOf(resultado);
            operacion = "nula";
            
        } else if (operacion.equals("restar")) {
            segundoNumero = Double.parseDouble(cadenaNumeros);
            resultado = primerNumero - segundoNumero;
            EtiquetaNumeros.setText(String.format("%.2f", resultado));
            cadenaNumeros = String.valueOf(resultado);
            operacion = "nula";

        } else if (operacion.equals("multiplicar")) {
            segundoNumero = Double.parseDouble(cadenaNumeros);
            resultado = primerNumero * segundoNumero;
            EtiquetaNumeros.setText(String.format("%.2f", resultado));
            cadenaNumeros = String.valueOf(resultado);
            operacion = "nula";
            
        } else if (operacion.equals("dividir")) {
            segundoNumero = Double.parseDouble(cadenaNumeros);
            resultado = primerNumero / segundoNumero;
            if (segundoNumero == 0) {
                EtiquetaNumeros.setText("No Se Puede Dividir Por 0");
                etiquetaMostrar.setText("");
                cadenaNumeros="";
                operacion="nula";
                activado=true;
                punto=true;
            } else {
                EtiquetaNumeros.setText(String.format("%.2f", resultado));
                cadenaNumeros = String.valueOf(resultado);
                operacion = "nula";
            }

        }
        etiquetaMostrar.setText("");
        activado=true;
        punto=false;
    }//GEN-LAST:event_botonIgualActionPerformed

    private void numero7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero7ActionPerformed

        if(EtiquetaNumeros.getText().equals("0")){
            cadenaNumeros="7";
        }else{
            cadenaNumeros+="7";
        }
        EtiquetaNumeros.setText(cadenaNumeros);
        activado=true;
    }//GEN-LAST:event_numero7ActionPerformed

    private void numero8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero8ActionPerformed
if(EtiquetaNumeros.getText().equals("0")){
            cadenaNumeros="8";
        }else{
            cadenaNumeros+="8";
        }
        EtiquetaNumeros.setText(cadenaNumeros);
        activado=true;

    }//GEN-LAST:event_numero8ActionPerformed

    private void numero9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero9ActionPerformed
if(EtiquetaNumeros.getText().equals("0")){
            cadenaNumeros="9";
        }else{
            cadenaNumeros+="9";
        }
        EtiquetaNumeros.setText(cadenaNumeros);
        activado=true;

    }//GEN-LAST:event_numero9ActionPerformed

    private void numero4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero4ActionPerformed

        if(EtiquetaNumeros.getText().equals("0")){
            cadenaNumeros="4";
        }else{
            cadenaNumeros+="4";
        }
        EtiquetaNumeros.setText(cadenaNumeros);
        activado=true;
    }//GEN-LAST:event_numero4ActionPerformed

    private void numero5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero5ActionPerformed

        if(EtiquetaNumeros.getText().equals("0")){
            cadenaNumeros="5";
        }else{
            cadenaNumeros+="5";
        }
        EtiquetaNumeros.setText(cadenaNumeros);
        activado=true;
    }//GEN-LAST:event_numero5ActionPerformed

    private void numero6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero6ActionPerformed

        if(EtiquetaNumeros.getText().equals("0")){
            cadenaNumeros="6";
        }else{
            cadenaNumeros+="6";
        }
        EtiquetaNumeros.setText(cadenaNumeros);
        activado=true;
    }//GEN-LAST:event_numero6ActionPerformed

    private void numero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero1ActionPerformed

        if(EtiquetaNumeros.getText().equals("0")){
            cadenaNumeros="1";
        }else{
            cadenaNumeros+="1";
        }
        EtiquetaNumeros.setText(cadenaNumeros);
        activado=true;
    }//GEN-LAST:event_numero1ActionPerformed

    private void numero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero2ActionPerformed

        if(EtiquetaNumeros.getText().equals("0")){
            cadenaNumeros="2";
        }else{
            cadenaNumeros+="2";
        }
        EtiquetaNumeros.setText(cadenaNumeros);
        activado=true;
    }//GEN-LAST:event_numero2ActionPerformed

    private void numero3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero3ActionPerformed

        if(EtiquetaNumeros.getText().equals("0")){
            cadenaNumeros="3";
        }else{
            cadenaNumeros+="3";
        }
        EtiquetaNumeros.setText(cadenaNumeros);
        activado=true;
    }//GEN-LAST:event_numero3ActionPerformed

    private void numero0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero0ActionPerformed

        if(EtiquetaNumeros.getText().equals("0")){
            cadenaNumeros="0";
        }else{
            cadenaNumeros+="0";
        }
        EtiquetaNumeros.setText(cadenaNumeros);
        activado=true;
    }//GEN-LAST:event_numero0ActionPerformed

    private void botonPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPuntoActionPerformed

        if(punto==true){
            if(cadenaNumeros.equals("")){
                cadenaNumeros="0.";
                
            }else{
                cadenaNumeros+=".";
                
            }
        }
        EtiquetaNumeros.setText(cadenaNumeros);
        punto=false;
    }//GEN-LAST:event_botonPuntoActionPerformed

    private void BotonMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMasActionPerformed

        if(activado=true){
            primerNumero=Double.parseDouble(cadenaNumeros);
            etiquetaMostrar.setText(cadenaNumeros+"+");
            cadenaNumeros="";
            operacion="sumar";
            EtiquetaNumeros.setText("0");
            
            
            activado=false;
            punto=true;
            
                    
        }
    }//GEN-LAST:event_BotonMasActionPerformed

    private void botonMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenosActionPerformed

        if(activado=true){
            primerNumero=Double.parseDouble(cadenaNumeros);
            etiquetaMostrar.setText(cadenaNumeros+"-");
            cadenaNumeros="";
            operacion="restar";
            EtiquetaNumeros.setText("0");
            
            activado=false;
            punto=true;
            
                    
        }
    }//GEN-LAST:event_botonMenosActionPerformed

    private void botonMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMultiplicarActionPerformed
        
        if(activado=true){
            primerNumero=Double.parseDouble(cadenaNumeros);
            etiquetaMostrar.setText(cadenaNumeros+"*");
            cadenaNumeros="";
            operacion="multiplicar";
            EtiquetaNumeros.setText("0");
            
            activado=false;
           punto=true;
                    
        }
    }//GEN-LAST:event_botonMultiplicarActionPerformed

    private void BotonDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDivisionActionPerformed
        if(activado=true){
            primerNumero=Double.parseDouble(cadenaNumeros);
            etiquetaMostrar.setText(cadenaNumeros+"/");
            cadenaNumeros="";
            operacion="dividir";
            EtiquetaNumeros.setText("0");
            
            activado=false;
           punto=true;
                    
        }
    }//GEN-LAST:event_BotonDivisionActionPerformed

    private void BotonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCActionPerformed

        etiquetaMostrar.setText("");
        EtiquetaNumeros.setText("0");
        cadenaNumeros="";
        operacion="nula";
        activado=true;
        punto=true;
        
        

    }//GEN-LAST:event_BotonCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonC;
    private javax.swing.JButton BotonDivision;
    private javax.swing.JButton BotonMas;
    private javax.swing.JButton BotonMmas;
    private javax.swing.JButton BotonMmenos;
    private javax.swing.JButton BotonR;
    private javax.swing.JLabel EtiquetaNumeros;
    private javax.swing.JButton botonIgual;
    private javax.swing.JButton botonMC;
    private javax.swing.JButton botonMR;
    private javax.swing.JButton botonMS;
    private javax.swing.JButton botonMenos;
    private javax.swing.JButton botonMultiplicar;
    private javax.swing.JButton botonPunto;
    private javax.swing.JLabel etiquetaMostrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton numero0;
    private javax.swing.JButton numero1;
    private javax.swing.JButton numero2;
    private javax.swing.JButton numero3;
    private javax.swing.JButton numero4;
    private javax.swing.JButton numero5;
    private javax.swing.JButton numero6;
    private javax.swing.JButton numero7;
    private javax.swing.JButton numero8;
    private javax.swing.JButton numero9;
    // End of variables declaration//GEN-END:variables
}
